### ISSUE TITLE
Option to disable snapping

### ISSUE THREAD

**Issue by literon36** [bakkeby/encircle#1]
First up a big thanks for making pretty much the exact thing I was looking for!

Secondly, it would be awesome if you could implement an option to _disable_ snapping!
I mainly just need the x-axis wrapping feature and kinda like my cursor getting stuck in the corners. (yes, I'm weird.)

Kind Regards!

**Comment by bakkeby** [comment]
You are right.

The existing behaviour of `-s` to _only_ enable snapping is kind of awkward; it makes more sense and is easier to explain if `-s` simply enables snapping.

Implementation wise it was more tricky than I thought, because I think that it still makes sense to keep snapping when doing outer mouse warping 

![image](https://github.com/bakkeby/encircle/assets/1438008/32101afa-2e8e-4cdc-babb-74f9cf3f21ba)

I.e. in the above example moving the mouse cursor to the hard edge (1) it would not snap to move over to the second monitor, but if you move to the left edge (2) then you would still want it to wrap around and move to the edge of the rightmost monitor.

The alternative would be to either:
   - wrap around the first monitor only if there is a hard edge (annoying) or
   - apply a hard edge on both sides if there is a hard edge on one side (complicated, especially if you have more than 2 monitors)

I'll push what I have so far anyway. Can you have a look to see if that works for your use-case?

**Comment by literon36** [comment]
Hey thanks for implementing it that quickly!
I currently have it installed via the AUR. Is it safe to install it with the Instructions provided and then overwrite it later once the updated version is released?

**Comment by bakkeby** [comment]
Yes should be perfectly fine. If you are unsure then you can just uninstall one before you install the other. Actually if you just clone and run `make` (rather than `sudo make install`) then the binary will be placed in the local directory and you can run ./encircle to test.

**Comment by literon36** [comment]
YES! `encircle -x` works like a charm and exactly how I want it to! Keep up the great work!
I think you can release this as an update now haha

**Comment by bakkeby** [comment]
Have pushed the update to the AUR now.
